### ISSUE TITLE
transaction hash

### ISSUE THREAD

**Issue by AlekseyLabunskiy777** [deblanco/tronix.js#12]
Hello everybody. I have a question. When I make a transaction through your application, it does not return the hash of this transaction. The answer is just empty. Here is an example of an answer. http://joxi.ru/nAyG8vPCYby6Vm
I use client.createTransaction (secret, from, to, amount) .then (function (res) {...}); Although transactions are normal. How do I get a hash of a new transaction? Thanks for the answer.

**Comment by deblanco** [comment]
Hi!

That is directly the response from the node, but is true that it’s useless without returning your transaction.
I’m gonna do a quick fix for that.

In the following weeks I’m going to release a new version with that will make it easier, please any feedback like this are welcome.

I’ll let you know when the new release is out.

Thanks 🙋‍♂️

**Comment by deblanco** [comment]
Hello again,

You have available the new version of the library (v0.0.6) that includes in the return the transaction data, included the Hash.

Thanks!

**Comment by AlekseyLabunskiy777** [comment]
Hello! Thanks for the answer! It works fine for hashes. There is one
more question. In SolidityGrpcClient there are methods
getTransactionsToThis and getTransactionsFromThis I so understood that
the information they take from SolidityNodes. On the page, there is a
link to public nodes.
https://github.com/tronprotocol/Documentation/blob/master/TRX/Official_Public_Node.md
The problem is that when I connect to these addresses and use these
methods for the test, I use different addresses, in return comes the
emptiness. Can you explain what I'm doing wrong?


Пт, 17 серп. 2018, 20:26 користувач Daniel Blanco Parla <
notifications@github.com> пише:
